AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - 'spec/**/*'
    - 'vendor/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 15

Style/Lambda:
  EnforcedStyle: literal

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Style/Documentation:
  Enabled: false