# syntax = docker/dockerfile:1

FROM ruby:3.2.2-alpine3.19

WORKDIR /google_books_client

# Install dependencies
RUN apk add --update --no-cache \
    build-base \
    openssl-dev \
    musl \
    git \
    cmake \
    bash

COPY . /google_books_client

# Install gems
RUN gem install bundler \
 && bundle install -j2 --retry 5 \
 && rm -rf /usr/local/bundle/cache/*.gem \
 && find /usr/local/bundle/gems/ -name "*.c" -delete \
 && find /usr/local/bundle/gems/ -name "*.o" -delete
