name: Ruby CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITH: development:test
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - name: Run lint
        run: bundle exec rubocop
      - name: Run tests
        run: bundle exec rspec